---

- hosts: localhost

  become: yes

  tasks:

    - name: Install Apache

      apt:

        name: apache2

        state: present

        update_cache: yes



    - name: Restart Apache

      service:

        name: apache2

        state: restarted
